# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.3.0
  hooks:
    - id: trailing-whitespace
      exclude: README\.md$
    - id: end-of-file-fixer
      exclude: (README\.md|setup\.cfg)$
    - id: check-ast
    - id: check-added-large-files
      args: [ '--maxkb=200' ]
    - id: check-merge-conflict
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: mixed-line-ending
      args: [ '--fix=lf' ]
