---
language: python

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.6'
    env: BUILD_SDIST=true
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.15
  - os: osx
    language: objective-c
    env:
    - PYENV_VERSION=3.6.5
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
    - BUILD_OSX_APP=true
  - os: linux
    python: 'pypy'


install:
  - |
    # Install
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        if [ ! -e "$HOME/.pyenv/.git" ]; then
            if [ -e "$HOME/.pyenv" ]; then
                rm -rf ~/.pyenv
            fi
            git clone https://github.com/pyenv/pyenv.git ~/.pyenv --depth 10
        else
            (cd ~/.pyenv; git pull)
        fi
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        hash -r
        eval "$(pyenv init -)"
        hash -r
        pyenv install --list
        pyenv install -s $PYENV_VERSION
        pyenv rehash
        pip install wheel
    fi
  - pip install coverage
  - pip install codecov
  - pip install .
  #- echo "Build $TRAVIS_BUILD_NUMBER BRANCH=$TRAVIS_BRANCH TAG=$TRAVIS_TAG"

script:
  - coverage run kintyre_speedtest.py

after_success:
  - codecov
  - if [[ $BUILD_SDIST == "true" && $TRAVIS_BRANCH =~ ^v.* ]]; then export DO_RELEASE=true; echo "Can we build it?  Yes we can!"; else echo "nah"; fi
  - |
    if [[ BUILD_OSX_APP == "true" && $TRAVIS_BRANCH =~ ^v.* ]]; then
        export BUILD_OSX_APP=now
        echo "Launching pyinstaller...."
        pip install pyinstaller
        pyinstaller kintyre_speedtest.py
        (cd dist; zip kintyre_speedtest-macosx-${TRAVIS_BRANCH}.zip -r kintyre_speedtest; )
    fi

deploy:
  # Push to GitHub releases
  - provider: releases
    api_key:
      secure: BDEpiA11Ua7h/gnncEbFyix6+l3HoPgc8YpXkwRZ69UDuSqgcMIKUIZrJsmU0sgTRG3rn2U2ArmEc10oK4Wx/dnKBNK3NHGMxWJxkJYEt1dXU8sa87vHpllKRp2pFAXSN2uU2CUe3Mi8OOG4xZwrNqSJuSrW5G4jbYl2JztDTdMagDnkUbhHIpx5kQENbzZp3Fgm8P/gEpeLrazqgc1c8QYa7yuYLSL7JgKH2OBiWMGbRbj6ecWjqYs4jqDBF5ezYJK0wJ5tXEMJx6EOkmqgk4OUExRHHKgLu964WFSZLvgee675sVLMhsp/prEiMUh2AfDR9JdynVGWHqLgCb2N0fJRZm/S16tG3v5HGhtMnAcK0rmphfWtQTUp+0RTjum2SPxVLt4ZVF2OTK+Q9vrc7pApf80PrRaZcM6umqCY1188A14nAm/NTugUAzRpcs0cquwcxqisGbaAGyAZtSZwK0BRX4wyl7bQAURJ6nc/HKqmsGbOUh0ezpXuUx8cuRbt/ztWXAskYFZAQPA+TMsuw4hun3lgBmhXDxCo1/xUO2Fsq3MlzaAKkeOsHTjP+NbipZcWcy7BgDYfqj0zREvIn73kY+NlifixHWs3KPkxaafkRCZ1L0yVgCM/amdD0uEIsMZWs5rIHfdGCZ4t228wsN5KHXath4S3MWl/MjxcN08=
    file: dist/kintyre*.zip
    file_glob: true
    skip_cleanup: true
    on:
      all_branches: true
      condition: $DO_RELEASE = "true"
  - provider: pypi
    user: lowellalleman
    password:
      secure: "tNuudCyNJuQtbBsMkYFjO+A7MzA8zJe2u6ynX8of3w8LFWyRG4Ip7zSejCXXD2RfsWgx7HfzX0RfkKtauvb+gKEb7679Ve7aYJa7E1tAJIBXZdsM7ioL6X+7O77WK+ogMwvra/6Tpkkn0RM+lRm02LJIu+BitQwHLk2PttpAEyrCuNs+FqV6XcLOoBcVkREBMrMtXi/xatT3+HQpywiMyPAINqEChUSavsOFIUMmzjz7vN021XZzOhnvdrkbUYQ0E9XoJjQmbJ53Fu5LjwupL2KdRHWvoUrafZ+0x0cZrffnJTjkhOBsQ7e0BbdIpGUI0dgK1JXtqga0MeebwlU1XIEUAhc/JxQZ3Z4ul9sevHuHD4oYLazS5BcCOhFc0BG0d3T4BqQRWdD1ddeR1aaWP2LtEbXalYE9xvtkY63X+/dxZCqJaCI0XWsU+odC3xD6r2tTAVK5GR+TrePMcWiXLUaHc6vgScUsKk6Cn/bbr9+cKS3/Rsk2mUMWbQGMdYCaCR/2fyvwZDnBrHmw197TnMhKePNDLBDii+8jFo+Kc4K11o0XfefnJSXeoC1hehvj6Jm+uNQ05okioCF3sdQ1FUtwrHG7/ISahndaq0R36+X3P2xo1NSmQ5pI++2psT0I5SGjBkHHd0mlgAYLyrop4km5chx5NRPV2GlNTXvcFUc="
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $BUILD_OSX_APP = "now"

notifications:
  email:
    - lowell@kintyre.co
